changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Security
      labels:
        - security
    - title: Protocol
      labels:
        - contracts
        - protocol
    - title: Interface
      labels:
        - frontend
        - accessibility
    - title: Quality and delivery
      labels:
        - testing
        - ci
        - documentation
    - title: Other changes
      labels:
        - "*"
