export default [
  {
    files: [
      "e2e/**/*.js",
      "release-tests/**/*.js",
      "playwright.config.js",
      "playwright.production.config.js",
      "scripts/verify-testnet-deployment.js",
      "scripts/validate-production-release.js",
      "scripts/lib/release-validation.js",
    ],
    languageOptions: {
      ecmaVersion: "latest",
      globals: {
        console: "readonly",
        document: "readonly",
        Error: "readonly",
        fetch: "readonly",
        Map: "readonly",
        Object: "readonly",
        process: "readonly",
        sessionStorage: "readonly",
        Set: "readonly",
        structuredClone: "readonly",
        URL: "readonly",
        window: "readonly",
      },
      sourceType: "module",
    },
    rules: {
      eqeqeq: "error",
      "no-constant-binary-expression": "error",
      "no-dupe-keys": "error",
      "no-redeclare": "error",
      "no-undef": "error",
      "no-unreachable": "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
];
